- name: Hello CAS Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello Cloud Automation Services!"
        
    - name: Install pip
      become: "true"
      apt: 
        name=python-pip state=present
      
    - name: install docker-py
      become: "true"
      pip: 
        name=docker-py
        
    - name: Running the container
      docker_container:
        image: moffzilla/httpd
        path: docker
        state: running

