- name: Hello CAS Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello Cloud Automation Services!"
        
- name: Hello CAS Sample
  become: true
  apt:
      name: "{{ item }}"
      state: present
  with_items:
      - htop
      - git
      - curl
      - unzip
      - make
      - ca-certificates
      - jq
      - ipcalc

