- name: Hello CAS Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello Cloud Automation Services!"
        
    - name: Install Apache
      raw: sudo apt install -y apache2

    - name: enabled mod_rewrite
      apache2_module: name=rewrite state=present
      notify:
        - restart apache2
  
  handlers:
    - name: restart apache2
      
