- name: Hello CAS Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello Cloud Automation Services!"
        
    - name: Create Apache container
      become: yes
      docker_container:
        name: my-apache-webserver
        image: "moffzilla/httpd"
        restart_policy: always
        volumes:
        - /mnt:/usr/local/apache2/htdocs/ 
        ports:
          - "80:80" 
      
