- name: Hello CAS Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello Cloud Automation Services!"
        
    - name: Database
      docker:
        name: database
        image: postgres:9.4
        state: started
      
